# default: &default
#   adapter: mysql2
#   encoding: utf8mb4
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

default: &default
  adapter: mysql2
  encoding: utf8
  collation: utf8_general_ci
  pool: 5
  host: <%= ENV['MYSQL_HOST'] || 'db' %>
  username: <%= ENV['MYSQL_USERNAME'] || 'root' %>
  password: <%= ENV['MYSQL_PASSWORD'] || 'password' %>
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: myapp_development
#   username: root
#   password: password
#   host: db

test:
  <<: *default
  database: myapp_test
#   username: root
#   password: password
#   host: <%=ENV['DB_HOST'] || '127.0.0.1' %>

production:
  <<: *default
  database: portfolio-db
  charset: utf8mb4
  collation: utf8mb4_general_ci
  username: <%= Rails.application.credentials.db[:user_name] %>
  password: <%= Rails.application.credentials.db[:password] %>
  host: <%= Rails.application.credentials.db[:endpoint] %>
  pool: 20
  timeout: 1000
